### ISSUE TITLE
100% CPU Usage

### ISSUE THREAD

**Issue by camronlevanger** [jasonlvhit/gocron#7]
Gocron is using 100% of one core, 100% of the time.

You don't even have to schedule anything, just calling gocron.Start() will do it.

Any thoughts?

**Comment by Claudiu** [comment]
This is related to: https://github.com/jasonlvhit/gocron/issues/3

The fix was merged with my repo but the usage is a bit different. 

As it now requires
```
<- gocron.Start()
```

**Comment by marksalpeter** [comment]
Yes, we merged in @Claudiu improvements. That should fix your problem. 
```
go get -u "github.com/jasonlvhit/gocron"
````
should fix the issue.

**Comment by danhardman** [comment]
Has there been any additional progress on this? I'm still getting 100% CPU usage when using this library unfortunately.

**Comment by marksalpeter** [comment]
have you pulled the latest version? you could also try the v1 branch.

**Comment by danhardman** [comment]
I believe so. I'll give it a go again to make sure. How do I get the v1 branch?

**Comment by marksalpeter** [comment]
```console
git checkout v1.0
```

**Comment by danhardman** [comment]
It was the latest version that I was getting the issue with. Just trying v1 now. Having to change some code around for it

**Comment by danhardman** [comment]
I'm getting error: `sch.Start() used as value` wherever I use `<-sch.Start()`

``` go
//Monitor checks the heating schedule at 1 minute intervals
func (s *Schedule) Monitor() {
	sch := gocron.NewScheduler()
	sch.Every(1).Minute().Do(s.checkSchedule)
	<-sch.Start()
}
```

**Comment by marksalpeter** [comment]
in the v1.0 branch start doesn't block or return anything. I haven't had a chance to update the docs though. From scheduler.go:

```go
// Scheduler keeps a slice of jobs that it executes at a regular interval
type Scheduler interface {
	// Start starts the scheduler
	Start()

	// IsRunning returns true if the job  has started
	IsRunning() bool

	// Stop stops the scheduler from executing jobs
	Stop()

   //  other methods ...
}
```

**Comment by danhardman** [comment]
Just found out it was likely not gocron causing the 100% CPU usage. I jumped to conclusions as I remembered seeing this issue! My bad. All is good
